name: Build check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Prepare:
    runs-on: ubuntu-latest
    outputs:
      rust_version: ${{ steps.read_toolchain.outputs.rust_version }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Read rustc version"
        id: read_toolchain
        run: echo "rust_version=$(cat rust-version)" >> $GITHUB_OUTPUT
  
  Check:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4
    - name: "Select toolchain"
      uses: dtolnay/rust-toolchain@stable
    - name: "Cargo check"
      run: cargo check
  
  Clippy:
    needs: Prepare
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4
    - name: "Select toolchain"
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ needs.Prepare.outputs.rust_version }}
    - name: "Install clippy"
      run: rustup component add clippy
    - name: "Lint"
      run: cargo clippy -- -D warnings
