name: Build check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      rust_version: ${{ steps.read_toolchain.outputs.rust_version }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Read rust version"
        id: read_toolchain
        run: echo "rust_version=$(cat rust-version)" >> $GITHUB_OUTPUT
  
  check-stable:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4
    - name: "Select toolchain"
      uses: dtolnay/rust-toolchain@stable
    - name: "Cargo check"
      run: cargo check
  
  format-and-lint:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4
    - name: "Select toolchain"
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ needs.Prepare.outputs.rust_version }}
        components: rustfmt, clippy
    - name: "rustfmt check"
      run: cargo fmt --all -- --check
    - name: "clippy"
      run: cargo clippy -- -D warnings
