name: Build check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Prepare:
    runs-on: ubuntu-latest
    outputs:
      rustc_version: ${{ steps.read_toolchain.outputs.rustc_version }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Read rustc version"
        id: read_toolchain
        run: echo "rustc_version=$(cat rustc-stable-version)" >> $GITHUB_OUTPUT
  
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4
    - name: "Install Rust"
      uses: dtolnay/rust-toolchain@stable
    - name: "Build"
      run: cargo build
  
  Clippy:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4
    - name: "Select toolchain"
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ needs.Prepare.outputs.rustc_version }}
    - name: "Install clippy"
      run: rustup component add clippy
    - name: "Lint"
      run: cargo clippy -- -D warnings
