name: Build check

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4
    - name: "Select toolchain"
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    - name: Rustfmt
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy -- -Dwarnings
  
  test:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4
    - name: "Select toolchain"
      uses: dtolnay/rust-toolchain@stable
    - name: Build + Test
      run: cargo test --lib
